import pygame

SCREEN_FLAGS = pygame.RESIZABLE | pygame.DOUBLEBUF
WIDTH = 450
HEIGHT = 490
RATIO = WIDTH/HEIGHT
CARD_WIDTH = 50
CARD_HEIGHT = 70
MARGIN = 10
BIG_MARGIN = 2*MARGIN
CARD_WIDTH_MARGIN = CARD_WIDTH + MARGIN
CARD_HEIGHT_MARGIN = CARD_HEIGHT + MARGIN
